language: go

go:
  - 1.2
  - 1.3
  - 1.4
  
install: 
  - sudo apt-get update || true
  - sudo apt-get install rrdtool librrd-dev
  - go get -t -v ./...

script: go build -v

notifications:
  email:
    - sapk@sapk.fr
